# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    master:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://10.5.80.179:1433;databaseName=OctOBackFT_1231;encrypt=true;trustServerCertificate=true
      username: pleung
      password: 123456
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
    slave:
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      #url: jdbc:oracle:thin:@10.11.198.16:1721:MSEUZ
      jdbc-url: jdbc:db2://192.168.20.20:50000/hksfo
      username: winvest
      password: PQ22wor6
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
